version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Debug - Check requests installation
          command: python -c "import requests; print('Requests version:', requests.__version__)"
      - run:
          name: Run unit tests
          command: python -m unittest discover

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
